language: node_js
sudo: false
node_js:
- '8'
cache: yarn
before_deploy: yarn run build
deploy:
  provider: npm
  email: sendstufftokevin@gmail.com
  api_key:
    secure: rPUVvCVA6X1nJexqnrCAV1B6P4SsQvNg1D2mEO6dvz5e04ECVRYJeQIh/rd2aWt4vH6rlpebD8OhgdncXCNnjTyuZzyO8A++ynXgPBSJTz3bPBuUgBkMNyF5pLXjN3infEsjlBrJPJvrg64hLDZq9p4H8kw++zdTRYmT2ttZoc5YQ3s0NUOyK9aIkapqtCaya7LzLJs/TC06Vd6g/UaP3yLHRxDYNlWImsxmAcg0Jfx4CnhPoieN9M0XJjXm7exJlRicrWbEWGHaSuhyMEESUjxxOdEL2g7ygEUHWy3aoVRPzJtLdONIy0KRhjam5oM5f2gRXZpgy9cmGP507zS8GE2D8UpjpaHCfNGQoDocNHciI/EEie8nj54YWypJ4xNO0wGqEG/ooMnp2V42As5sTuv1pw67Xq/h8Zrq/oy5+YWhA2sca3mIFprjNfYX5Lv3Xqrj3ZbyStl58+FWBFhBLbulNiRz8q4DdjtoNHLB198hV/tttJnncqGqaUzmU9GWLvoRFvv/VatXh4qyowpnzmsJD75hgCnxZTENC12GaOZh06T6MxPm1kt7zd26Kl+0FufUg6hFaM2SxyXTaY0N1mfitB/bdYdv/PR8z4jCnKBMsHyItufR2ZpIwRc3LvYZRLXPeDJGwjjiKlq9T0nHN9uemct2xjNa3DuNColaO1U=
  on:
    branch: master
    tags: true
  skip_cleanup: true
